extends Node

signal bullet_hit (player_damage)
signal exp_changed (experience)
signal health_changed (health)
signal health_upgraded (health)
signal Riflebullet_hit (player_damage)
signal Uzibullet_hit (player_damage)
signal Karbullet_hit (player_damage)
signal Shotgunbullet_hit (player_damage)
signal rifle_fire ()
signal pistol_fire ()
signal uzi_fire ()
signal kar98k_fire ()
signal shotgun_fire ()
signal Stump_hit ()
signal Upgradetime ()
signal SellItem ()
signal Worm_hit ()
signal Flower_hit ()
signal WormBulletHit ()
signal FlowerBulletHit ()
signal Return_damage_worm (returned_damage)
signal Return_damage_stump (returned_damage)
signal Return_damage_flower (returned_damage)
signal MISS ()
signal sword_slash ()
